"""initial_schema

Revision ID: 1fa1c26ec5be
Revises: 
Create Date: 2026-03-26 00:16:26.744719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa1c26ec5be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('itinerary_revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('disruption_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('disruption_type', sa.String(length=64), nullable=True),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruption_events_proposal_id'), 'disruption_events', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_disruption_events_trip_id'), 'disruption_events', ['trip_id'], unique=False)
    op.create_index(op.f('ix_disruption_events_user_id'), 'disruption_events', ['user_id'], unique=False)
    op.create_table('itinerary_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('segment_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_segments_trip_id'), 'itinerary_segments', ['trip_id'], unique=False)
    op.create_table('rebooking_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('selected_offer_id', sa.String(length=128), nullable=True),
    sa.Column('duffel_order_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rebooking_proposals_trip_id'), 'rebooking_proposals', ['trip_id'], unique=False)
    op.create_index(op.f('ix_rebooking_proposals_user_id'), 'rebooking_proposals', ['user_id'], unique=False)
    op.create_table('trip_legs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('segment_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mode', sa.String(length=16), server_default='flight', nullable=False),
    sa.Column('origin_code', sa.String(length=16), nullable=False),
    sa.Column('destination_code', sa.String(length=16), nullable=False),
    sa.Column('flight_number', sa.String(length=32), nullable=True),
    sa.Column('travel_date', sa.String(length=16), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_legs_trip_id'), 'trip_legs', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_legs_trip_id'), table_name='trip_legs')
    op.drop_table('trip_legs')
    op.drop_index(op.f('ix_rebooking_proposals_user_id'), table_name='rebooking_proposals')
    op.drop_index(op.f('ix_rebooking_proposals_trip_id'), table_name='rebooking_proposals')
    op.drop_table('rebooking_proposals')
    op.drop_index(op.f('ix_itinerary_segments_trip_id'), table_name='itinerary_segments')
    op.drop_table('itinerary_segments')
    op.drop_index(op.f('ix_disruption_events_user_id'), table_name='disruption_events')
    op.drop_index(op.f('ix_disruption_events_trip_id'), table_name='disruption_events')
    op.drop_index(op.f('ix_disruption_events_proposal_id'), table_name='disruption_events')
    op.drop_table('disruption_events')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
