/** Major airports for datalist / quick lookup (IATA + city). No external API. */

export type AirportEntry = { iata: string; city: string; country: string };

export const AIRPORTS: AirportEntry[] = [
  { iata: "ATL", city: "Atlanta", country: "US" },
  { iata: "LAX", city: "Los Angeles", country: "US" },
  { iata: "ORD", city: "Chicago O'Hare", country: "US" },
  { iata: "DFW", city: "Dallas/Fort Worth", country: "US" },
  { iata: "DEN", city: "Denver", country: "US" },
  { iata: "JFK", city: "New York JFK", country: "US" },
  { iata: "SFO", city: "San Francisco", country: "US" },
  { iata: "SEA", city: "Seattle", country: "US" },
  { iata: "LAS", city: "Las Vegas", country: "US" },
  { iata: "MCO", city: "Orlando", country: "US" },
  { iata: "EWR", city: "Newark", country: "US" },
  { iata: "CLT", city: "Charlotte", country: "US" },
  { iata: "PHX", city: "Phoenix", country: "US" },
  { iata: "IAH", city: "Houston", country: "US" },
  { iata: "MIA", city: "Miami", country: "US" },
  { iata: "BOS", city: "Boston", country: "US" },
  { iata: "MSP", city: "Minneapolis", country: "US" },
  { iata: "DTW", city: "Detroit", country: "US" },
  { iata: "PHL", city: "Philadelphia", country: "US" },
  { iata: "LGA", city: "New York LaGuardia", country: "US" },
  { iata: "BWI", city: "Baltimore", country: "US" },
  { iata: "SLC", city: "Salt Lake City", country: "US" },
  { iata: "IAD", city: "Washington Dulles", country: "US" },
  { iata: "DCA", city: "Washington Reagan", country: "US" },
  { iata: "SAN", city: "San Diego", country: "US" },
  { iata: "PDX", city: "Portland OR", country: "US" },
  { iata: "STL", city: "St. Louis", country: "US" },
  { iata: "BNA", city: "Nashville", country: "US" },
  { iata: "AUS", city: "Austin", country: "US" },
  { iata: "TPA", city: "Tampa", country: "US" },
  { iata: "HNL", city: "Honolulu", country: "US" },
  { iata: "YVR", city: "Vancouver", country: "CA" },
  { iata: "YYZ", city: "Toronto Pearson", country: "CA" },
  { iata: "YUL", city: "Montreal", country: "CA" },
  { iata: "YYC", city: "Calgary", country: "CA" },
  { iata: "LHR", city: "London Heathrow", country: "GB" },
  { iata: "LGW", city: "London Gatwick", country: "GB" },
  { iata: "MAN", city: "Manchester", country: "GB" },
  { iata: "EDI", city: "Edinburgh", country: "GB" },
  { iata: "DUB", city: "Dublin", country: "IE" },
  { iata: "CDG", city: "Paris CDG", country: "FR" },
  { iata: "ORY", city: "Paris Orly", country: "FR" },
  { iata: "AMS", city: "Amsterdam", country: "NL" },
  { iata: "FRA", city: "Frankfurt", country: "DE" },
  { iata: "MUC", city: "Munich", country: "DE" },
  { iata: "ZRH", city: "Zurich", country: "CH" },
  { iata: "VIE", city: "Vienna", country: "AT" },
  { iata: "MAD", city: "Madrid", country: "ES" },
  { iata: "BCN", city: "Barcelona", country: "ES" },
  { iata: "LIS", city: "Lisbon", country: "PT" },
  { iata: "FCO", city: "Rome Fiumicino", country: "IT" },
  { iata: "MXP", city: "Milan Malpensa", country: "IT" },
  { iata: "ATH", city: "Athens", country: "GR" },
  { iata: "IST", city: "Istanbul", country: "TR" },
  { iata: "DXB", city: "Dubai", country: "AE" },
  { iata: "DOH", city: "Doha", country: "QA" },
  { iata: "SIN", city: "Singapore", country: "SG" },
  { iata: "HKG", city: "Hong Kong", country: "HK" },
  { iata: "NRT", city: "Tokyo Narita", country: "JP" },
  { iata: "HND", city: "Tokyo Haneda", country: "JP" },
  { iata: "ICN", city: "Seoul", country: "KR" },
  { iata: "PEK", city: "Beijing", country: "CN" },
  { iata: "PVG", city: "Shanghai Pudong", country: "CN" },
  { iata: "BOM", city: "Mumbai", country: "IN" },
  { iata: "DEL", city: "New Delhi", country: "IN" },
  { iata: "BLR", city: "Bengaluru", country: "IN" },
  { iata: "HYD", city: "Hyderabad", country: "IN" },
  { iata: "MAA", city: "Chennai", country: "IN" },
  { iata: "CCU", city: "Kolkata", country: "IN" },
  { iata: "COK", city: "Kochi", country: "IN" },
  { iata: "SYD", city: "Sydney", country: "AU" },
  { iata: "MEL", city: "Melbourne", country: "AU" },
  { iata: "BNE", city: "Brisbane", country: "AU" },
  { iata: "AKL", city: "Auckland", country: "NZ" },
  { iata: "GRU", city: "São Paulo", country: "BR" },
  { iata: "GIG", city: "Rio de Janeiro", country: "BR" },
  { iata: "MEX", city: "Mexico City", country: "MX" },
  { iata: "CUN", city: "Cancún", country: "MX" },
  { iata: "PTY", city: "Panama City", country: "PA" },
  { iata: "BOG", city: "Bogotá", country: "CO" },
  { iata: "LIM", city: "Lima", country: "PE" },
  { iata: "SCL", city: "Santiago", country: "CL" },
  { iata: "EZE", city: "Buenos Aires", country: "AR" },
  { iata: "JNB", city: "Johannesburg", country: "ZA" },
  { iata: "CPT", city: "Cape Town", country: "ZA" },
  { iata: "CAI", city: "Cairo", country: "EG" },
  { iata: "ADD", city: "Addis Ababa", country: "ET" },
  { iata: "NBO", city: "Nairobi", country: "KE" },
];

export function airportDatalistOptions(): string {
  return AIRPORTS.map((a) => `${a.iata} — ${a.city}`).join("\n");
}

export function findAirportByIata(iata: string): AirportEntry | undefined {
  const c = iata.trim().toUpperCase();
  return AIRPORTS.find((a) => a.iata === c);
}
